# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np

tables_and_columns = {
    'meter': [
        'meter_id',
        'cis_cust_id',
        'cis_location_id',
        'location_id',
#        'data_set_id',
        'cust_type',
        'cust_type_code',
        'meter_type',
        'meter_size',
        'meter_size_units',
        'meter_size_lowflow',
        'num_units',
    ],
    'meter_location': [
        'location_id',
        'cis_location_id',
#        'data_set_id',
        'latitude',
        'longitude',
        'meter_address',
        'municipality',
#        'subdivision',
        'route',
#        'experimental_group',
#        'shared_premise_identifier',
        'aggregate_cust_type_code',
    ],
    'occupant': [
        'id',
        'location_id',
        'cis_occupant_id',
#        'data_set_id',
        'move_in_date',
        'move_out_date',
    ],
    'cutoffs': [
        'id',
        'location_id',
        'cis_occupant_id',
#        'data_set_id',
        'cutoff_at',
    ],
    'volume': [
        'meter_id',
        'charge_id',
#        'data_set_id',
        'meter_read_at',
#        'fiscal_year',
        'volume_kgals',
#        'volume_unit',
        'unbilled',
#        'days_diff',
    ],
    'rate_table_vol': [
        'rate_code',
        'min_volume_kgals',
        'price_per_kgal',
        'max_volume_kgals',
        'rate_started_at',
        'rate_ended_at',
    ],
    'charge': [
        'charge_id',
        'cis_bill_id',
        'location_id',
#        'data_set_id',
        'billing_period_end',
#        'fiscal_year',
#        'days_diff',
        'base_charge',
        'vol_charge',
        'total_charge',
        'late_charge',
        'tampering_charge',
#        'special_rate_account',
#        'zero_bill_account',
#        'other_charge',
#        'rate_code',
#        'payment_arrangement',
#        'prorated',
#        'estimated',
    ],
}

